import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:vroom/core/localization/app_language.dart';

class AppLocalizations {
  const AppLocalizations(this.language);

  static const delegate = _AppLocalizationsDelegate();

  final AppLanguage language;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        const AppLocalizations(AppLanguage.defaultLanguage);
  }

  static AppLocalizations forLanguage(AppLanguage language) {
    return AppLocalizations(language);
  }

  String get chooseLanguageTitle => _t('chooseLanguageTitle');
  String get chooseLanguageSubtitle => _t('chooseLanguageSubtitle');
  String get continueAction => _t('continueAction');
  String get profileLanguageTitle => _t('profileLanguageTitle');
  String get profileLanguageSubtitle => _t('profileLanguageSubtitle');
  String get profileLanguagePickerTitle => _t('profileLanguagePickerTitle');
  String get onboardingSkip => _t('onboardingSkip');
  String get onboardingNext => _t('onboardingNext');
  String get onboardingStart => _t('onboardingStart');
  String get onboardingWelcomeTitle => _t('onboardingWelcomeTitle');
  String get onboardingWelcomeDescription => _t('onboardingWelcomeDescription');
  String get onboardingProfessionTitle => _t('onboardingProfessionTitle');
  String get onboardingProfessionDescription =>
      _t('onboardingProfessionDescription');
  String get onboardingAchievementsTitle => _t('onboardingAchievementsTitle');
  String get onboardingAchievementsDescription =>
      _t('onboardingAchievementsDescription');
  String get navHome => _t('navHome');
  String get navProfile => _t('navProfile');
  String get profileJoinedEvents => _t('profileJoinedEvents');
  String get profileScannedQuests => _t('profileScannedQuests');
  String get profileAchievements => _t('profileAchievements');
  String get profileRecentActivities => _t('profileRecentActivities');
  String get profileLogout => _t('profileLogout');
  String get profileLoadFailed => _t('profileLoadFailed');
  String get profileUnavailable => _t('profileUnavailable');
  String get genericError => _t('genericError');
  String get homeGreeting => _t('homeGreeting');
  String get homeEventsTitle => _t('homeEventsTitle');
  String get homeEmptyEvents => _t('homeEmptyEvents');
  String get homeLoadFailed => _t('homeLoadFailed');
  String get loginSubtitle => _t('loginSubtitle');
  String get loginFieldLogin => _t('loginFieldLogin');
  String get loginFieldPassword => _t('loginFieldPassword');
  String get loginButton => _t('loginButton');
  String get loginQrButton => _t('loginQrButton');
  String get loginNoAccount => _t('loginNoAccount');
  String get loginRegisterLink => _t('loginRegisterLink');
  String get registerTitle => _t('registerTitle');
  String get registerSubtitle => _t('registerSubtitle');
  String get firstName => _t('firstName');
  String get lastName => _t('lastName');
  String get registerButton => _t('registerButton');
  String get alreadyHaveAccount => _t('alreadyHaveAccount');
  String get qrManualTitle => _t('qrManualTitle');
  String get qrManualHint => _t('qrManualHint');
  String get cancel => _t('cancel');
  String get open => _t('open');
  String get qrScannerTitle => _t('qrScannerTitle');
  String get qrScannerHint => _t('qrScannerHint');
  String get qrProcessing => _t('qrProcessing');
  String get qrManualButton => _t('qrManualButton');

  String welcomeUser(String login) {
    return _t('welcomeUser').replaceAll('{login}', login);
  }

  String _t(String key) {
    return _localizedValues[language]?[key] ??
        _localizedValues[AppLanguage.english]![key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLanguage.tryFromCode(locale.languageCode) != null;
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(
      AppLocalizations(AppLanguage.fromLocale(locale)),
    );
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

const _localizedValues = <AppLanguage, Map<String, String>>{
  AppLanguage.russian: {
    'chooseLanguageTitle': 'Выберите язык',
    'chooseLanguageSubtitle': 'Выберите предпочитаемый язык',
    'continueAction': 'Продолжить',
    'profileLanguageTitle': 'Язык',
    'profileLanguageSubtitle': 'Язык интерфейса приложения',
    'profileLanguagePickerTitle': 'Выберите язык',
    'onboardingSkip': 'Пропустить',
    'onboardingNext': 'Далее',
    'onboardingStart': 'Начать',
    'onboardingWelcomeTitle': 'Добро пожаловать в ARient',
    'onboardingWelcomeDescription':
        'Исследуй профессии будущего через AR-квесты с дополненной реальностью',
    'onboardingProfessionTitle': 'Погрузись в профессию',
    'onboardingProfessionDescription':
        'Попробуй себя в роли инженера, врача, дизайнера в дополненной реальности',
    'onboardingAchievementsTitle': 'Получай достижения',
    'onboardingAchievementsDescription':
        'Проходи квесты, отвечай на вопросы и открывай новые награды',
    'navHome': 'Главная',
    'navProfile': 'Профиль',
    'profileJoinedEvents': 'Мероприятий',
    'profileScannedQuests': 'Сканированных квестов',
    'profileAchievements': 'Достижения',
    'profileRecentActivities': 'Последние активности',
    'profileLogout': 'Выйти',
    'profileLoadFailed': 'Не удалось загрузить профиль',
    'profileUnavailable': 'Профиль недоступен',
    'genericError': 'Что-то пошло не так',
    'homeGreeting': 'Привет,',
    'homeEventsTitle': 'Мои мероприятия',
    'homeEmptyEvents': 'Вы пока не присоединились ни к одному мероприятию.',
    'homeLoadFailed': 'Не удалось загрузить мероприятия',
    'loginSubtitle': 'Войди и начни исследовать',
    'loginFieldLogin': 'Логин',
    'loginFieldPassword': 'Пароль',
    'loginButton': 'Войти',
    'loginQrButton': 'Войти по QR-коду',
    'loginNoAccount': 'Нет аккаунта?',
    'loginRegisterLink': 'Зарегистрируйся',
    'registerTitle': 'Регистрация',
    'registerSubtitle': 'Создай аккаунт и начни путешествие',
    'firstName': 'Имя',
    'lastName': 'Фамилия',
    'registerButton': 'Зарегистрироваться',
    'alreadyHaveAccount': 'Уже есть аккаунт?',
    'welcomeUser': 'Добро пожаловать, {login}!',
    'qrManualTitle': 'Введите QR-код',
    'qrManualHint': 'Токен или значение QR',
    'cancel': 'Отмена',
    'open': 'Открыть',
    'qrScannerTitle': 'Сканер QR-кода',
    'qrScannerHint': 'Наведите камеру на QR-код',
    'qrProcessing': 'Обработка...',
    'qrManualButton': 'Ввести код вручную',
  },
  AppLanguage.english: {
    'chooseLanguageTitle': 'Choose Your Language',
    'chooseLanguageSubtitle': 'Select your preferred language',
    'continueAction': 'Continue',
    'profileLanguageTitle': 'Language',
    'profileLanguageSubtitle': 'App interface language',
    'profileLanguagePickerTitle': 'Choose language',
    'onboardingSkip': 'Skip',
    'onboardingNext': 'Next',
    'onboardingStart': 'Start',
    'onboardingWelcomeTitle': 'Welcome to ARient',
    'onboardingWelcomeDescription':
        'Explore future careers through augmented reality AR quests',
    'onboardingProfessionTitle': 'Step into a profession',
    'onboardingProfessionDescription':
        'Try being an engineer, doctor, or designer in augmented reality',
    'onboardingAchievementsTitle': 'Earn achievements',
    'onboardingAchievementsDescription':
        'Complete quests, answer questions, and unlock new rewards',
    'navHome': 'Home',
    'navProfile': 'Profile',
    'profileJoinedEvents': 'Events',
    'profileScannedQuests': 'Scanned quests',
    'profileAchievements': 'Achievements',
    'profileRecentActivities': 'Recent activities',
    'profileLogout': 'Log out',
    'profileLoadFailed': 'Could not load profile',
    'profileUnavailable': 'Profile unavailable',
    'genericError': 'Something went wrong',
    'homeGreeting': 'Hi,',
    'homeEventsTitle': 'My events',
    'homeEmptyEvents': 'No events joined yet.',
    'homeLoadFailed': 'Could not load events',
    'loginSubtitle': 'Sign in and start exploring',
    'loginFieldLogin': 'Login',
    'loginFieldPassword': 'Password',
    'loginButton': 'Sign in',
    'loginQrButton': 'Sign in with QR code',
    'loginNoAccount': 'No account?',
    'loginRegisterLink': 'Sign up',
    'registerTitle': 'Registration',
    'registerSubtitle': 'Create an account and start the journey',
    'firstName': 'First name',
    'lastName': 'Last name',
    'registerButton': 'Create account',
    'alreadyHaveAccount': 'Already have an account?',
    'welcomeUser': 'Welcome, {login}!',
    'qrManualTitle': 'Enter QR code',
    'qrManualHint': 'Token or QR value',
    'cancel': 'Cancel',
    'open': 'Open',
    'qrScannerTitle': 'QR code scanner',
    'qrScannerHint': 'Point the camera at the QR code',
    'qrProcessing': 'Processing...',
    'qrManualButton': 'Enter code manually',
  },
  AppLanguage.turkish: {
    'chooseLanguageTitle': 'Dilinizi Seçin',
    'chooseLanguageSubtitle': 'Tercih ettiğiniz dili seçin',
    'continueAction': 'Devam',
    'profileLanguageTitle': 'Dil',
    'profileLanguageSubtitle': 'Uygulama arayüz dili',
    'profileLanguagePickerTitle': 'Dil seçin',
    'onboardingSkip': 'Atla',
    'onboardingNext': 'İleri',
    'onboardingStart': 'Başla',
    'onboardingWelcomeTitle': 'ARient ile tanışın',
    'onboardingWelcomeDescription':
        'Geleceğin mesleklerini artırılmış gerçeklik görevleriyle keşfedin',
    'onboardingProfessionTitle': 'Bir mesleğe adım atın',
    'onboardingProfessionDescription':
        'Artırılmış gerçeklikte mühendis, doktor veya tasarımcı rolünü deneyin',
    'onboardingAchievementsTitle': 'Başarılar kazanın',
    'onboardingAchievementsDescription':
        'Görevleri tamamlayın, soruları yanıtlayın ve yeni ödüller açın',
    'navHome': 'Ana sayfa',
    'navProfile': 'Profil',
    'profileJoinedEvents': 'Etkinlikler',
    'profileScannedQuests': 'Taranan görevler',
    'profileAchievements': 'Başarılar',
    'profileRecentActivities': 'Son aktiviteler',
    'profileLogout': 'Çıkış yap',
    'profileLoadFailed': 'Profil yüklenemedi',
    'profileUnavailable': 'Profil kullanılamıyor',
    'genericError': 'Bir şeyler ters gitti',
    'homeGreeting': 'Merhaba,',
    'homeEventsTitle': 'Etkinliklerim',
    'homeEmptyEvents': 'Henüz hiçbir etkinliğe katılmadınız.',
    'homeLoadFailed': 'Etkinlikler yüklenemedi',
    'loginSubtitle': 'Giriş yapın ve keşfetmeye başlayın',
    'loginFieldLogin': 'Giriş',
    'loginFieldPassword': 'Şifre',
    'loginButton': 'Giriş yap',
    'loginQrButton': 'QR kod ile giriş yap',
    'loginNoAccount': 'Hesabınız yok mu?',
    'loginRegisterLink': 'Kaydol',
    'registerTitle': 'Kayıt',
    'registerSubtitle': 'Hesap oluşturun ve yolculuğa başlayın',
    'firstName': 'Ad',
    'lastName': 'Soyad',
    'registerButton': 'Hesap oluştur',
    'alreadyHaveAccount': 'Zaten hesabınız var mı?',
    'welcomeUser': 'Hoş geldiniz, {login}!',
    'qrManualTitle': 'QR kodu girin',
    'qrManualHint': 'Token veya QR değeri',
    'cancel': 'İptal',
    'open': 'Aç',
    'qrScannerTitle': 'QR kod tarayıcı',
    'qrScannerHint': 'Kamerayı QR koda doğrultun',
    'qrProcessing': 'İşleniyor...',
    'qrManualButton': 'Kodu elle gir',
  },
  AppLanguage.arabic: {
    'chooseLanguageTitle': 'اختر لغتك',
    'chooseLanguageSubtitle': 'اختر اللغة المفضلة لديك',
    'continueAction': 'متابعة',
    'profileLanguageTitle': 'اللغة',
    'profileLanguageSubtitle': 'لغة واجهة التطبيق',
    'profileLanguagePickerTitle': 'اختر اللغة',
    'onboardingSkip': 'تخطي',
    'onboardingNext': 'التالي',
    'onboardingStart': 'ابدأ',
    'onboardingWelcomeTitle': 'مرحبًا بك في ARient',
    'onboardingWelcomeDescription': 'اكتشف مهن المستقبل عبر مهام الواقع المعزز',
    'onboardingProfessionTitle': 'انغمس في المهنة',
    'onboardingProfessionDescription':
        'جرّب دور المهندس أو الطبيب أو المصمم في الواقع المعزز',
    'onboardingAchievementsTitle': 'احصل على إنجازات',
    'onboardingAchievementsDescription':
        'أكمل المهام وأجب عن الأسئلة وافتح مكافآت جديدة',
    'navHome': 'الرئيسية',
    'navProfile': 'الملف الشخصي',
    'profileJoinedEvents': 'الفعاليات',
    'profileScannedQuests': 'المهام الممسوحة',
    'profileAchievements': 'الإنجازات',
    'profileRecentActivities': 'آخر الأنشطة',
    'profileLogout': 'تسجيل الخروج',
    'profileLoadFailed': 'تعذر تحميل الملف الشخصي',
    'profileUnavailable': 'الملف الشخصي غير متاح',
    'genericError': 'حدث خطأ ما',
    'homeGreeting': 'مرحبًا،',
    'homeEventsTitle': 'فعالياتي',
    'homeEmptyEvents': 'لم تنضم إلى أي فعالية بعد.',
    'homeLoadFailed': 'تعذر تحميل الفعاليات',
    'loginSubtitle': 'سجّل الدخول وابدأ الاستكشاف',
    'loginFieldLogin': 'اسم الدخول',
    'loginFieldPassword': 'كلمة المرور',
    'loginButton': 'تسجيل الدخول',
    'loginQrButton': 'تسجيل الدخول عبر رمز QR',
    'loginNoAccount': 'ليس لديك حساب؟',
    'loginRegisterLink': 'إنشاء حساب',
    'registerTitle': 'التسجيل',
    'registerSubtitle': 'أنشئ حسابًا وابدأ الرحلة',
    'firstName': 'الاسم',
    'lastName': 'اسم العائلة',
    'registerButton': 'إنشاء حساب',
    'alreadyHaveAccount': 'لديك حساب بالفعل؟',
    'welcomeUser': 'مرحبًا، {login}!',
    'qrManualTitle': 'أدخل رمز QR',
    'qrManualHint': 'الرمز أو قيمة QR',
    'cancel': 'إلغاء',
    'open': 'فتح',
    'qrScannerTitle': 'ماسح رمز QR',
    'qrScannerHint': 'وجّه الكاميرا نحو رمز QR',
    'qrProcessing': 'جارٍ المعالجة...',
    'qrManualButton': 'إدخال الرمز يدويًا',
  },
  AppLanguage.german: {
    'chooseLanguageTitle': 'Sprache auswählen',
    'chooseLanguageSubtitle': 'Wählen Sie Ihre bevorzugte Sprache',
    'continueAction': 'Weiter',
    'profileLanguageTitle': 'Sprache',
    'profileLanguageSubtitle': 'Sprache der App-Oberfläche',
    'profileLanguagePickerTitle': 'Sprache auswählen',
    'onboardingSkip': 'Überspringen',
    'onboardingNext': 'Weiter',
    'onboardingStart': 'Starten',
    'onboardingWelcomeTitle': 'Willkommen bei ARient',
    'onboardingWelcomeDescription':
        'Entdecken Sie Berufe der Zukunft mit AR-Quests',
    'onboardingProfessionTitle': 'Tauchen Sie in den Beruf ein',
    'onboardingProfessionDescription':
        'Probieren Sie die Rolle von Ingenieur, Arzt oder Designer in AR aus',
    'onboardingAchievementsTitle': 'Sammeln Sie Erfolge',
    'onboardingAchievementsDescription':
        'Schließen Sie Quests ab, beantworten Sie Fragen und schalten Sie Belohnungen frei',
    'navHome': 'Start',
    'navProfile': 'Profil',
    'profileJoinedEvents': 'Events',
    'profileScannedQuests': 'Gescannte Quests',
    'profileAchievements': 'Erfolge',
    'profileRecentActivities': 'Letzte Aktivitäten',
    'profileLogout': 'Abmelden',
    'profileLoadFailed': 'Profil konnte nicht geladen werden',
    'profileUnavailable': 'Profil nicht verfügbar',
    'genericError': 'Etwas ist schiefgelaufen',
    'homeGreeting': 'Hallo,',
    'homeEventsTitle': 'Meine Events',
    'homeEmptyEvents': 'Sie sind noch keinem Event beigetreten.',
    'homeLoadFailed': 'Events konnten nicht geladen werden',
    'loginSubtitle': 'Melden Sie sich an und beginnen Sie die Erkundung',
    'loginFieldLogin': 'Login',
    'loginFieldPassword': 'Passwort',
    'loginButton': 'Anmelden',
    'loginQrButton': 'Mit QR-Code anmelden',
    'loginNoAccount': 'Noch kein Konto?',
    'loginRegisterLink': 'Registrieren',
    'registerTitle': 'Registrierung',
    'registerSubtitle': 'Erstellen Sie ein Konto und starten Sie die Reise',
    'firstName': 'Vorname',
    'lastName': 'Nachname',
    'registerButton': 'Konto erstellen',
    'alreadyHaveAccount': 'Sie haben bereits ein Konto?',
    'welcomeUser': 'Willkommen, {login}!',
    'qrManualTitle': 'QR-Code eingeben',
    'qrManualHint': 'Token oder QR-Wert',
    'cancel': 'Abbrechen',
    'open': 'Öffnen',
    'qrScannerTitle': 'QR-Code-Scanner',
    'qrScannerHint': 'Richten Sie die Kamera auf den QR-Code',
    'qrProcessing': 'Verarbeitung...',
    'qrManualButton': 'Code manuell eingeben',
  },
  AppLanguage.spanish: {
    'chooseLanguageTitle': 'Elige tu idioma',
    'chooseLanguageSubtitle': 'Selecciona tu idioma preferido',
    'continueAction': 'Continuar',
    'profileLanguageTitle': 'Idioma',
    'profileLanguageSubtitle': 'Idioma de la interfaz',
    'profileLanguagePickerTitle': 'Elige idioma',
    'onboardingSkip': 'Omitir',
    'onboardingNext': 'Siguiente',
    'onboardingStart': 'Comenzar',
    'onboardingWelcomeTitle': 'Bienvenido a ARient',
    'onboardingWelcomeDescription':
        'Explora profesiones del futuro con misiones de realidad aumentada',
    'onboardingProfessionTitle': 'Sumérgete en la profesión',
    'onboardingProfessionDescription':
        'Prueba el rol de ingeniero, médico o diseñador en realidad aumentada',
    'onboardingAchievementsTitle': 'Consigue logros',
    'onboardingAchievementsDescription':
        'Completa misiones, responde preguntas y desbloquea recompensas',
    'navHome': 'Inicio',
    'navProfile': 'Perfil',
    'profileJoinedEvents': 'Eventos',
    'profileScannedQuests': 'Misiones escaneadas',
    'profileAchievements': 'Logros',
    'profileRecentActivities': 'Actividad reciente',
    'profileLogout': 'Cerrar sesión',
    'profileLoadFailed': 'No se pudo cargar el perfil',
    'profileUnavailable': 'Perfil no disponible',
    'genericError': 'Algo salió mal',
    'homeGreeting': 'Hola,',
    'homeEventsTitle': 'Mis eventos',
    'homeEmptyEvents': 'Todavía no te has unido a ningún evento.',
    'homeLoadFailed': 'No se pudieron cargar los eventos',
    'loginSubtitle': 'Inicia sesión y empieza a explorar',
    'loginFieldLogin': 'Usuario',
    'loginFieldPassword': 'Contraseña',
    'loginButton': 'Iniciar sesión',
    'loginQrButton': 'Entrar con código QR',
    'loginNoAccount': '¿No tienes cuenta?',
    'loginRegisterLink': 'Regístrate',
    'registerTitle': 'Registro',
    'registerSubtitle': 'Crea una cuenta y comienza el viaje',
    'firstName': 'Nombre',
    'lastName': 'Apellido',
    'registerButton': 'Crear cuenta',
    'alreadyHaveAccount': '¿Ya tienes cuenta?',
    'welcomeUser': '¡Bienvenido, {login}!',
    'qrManualTitle': 'Introduce el código QR',
    'qrManualHint': 'Token o valor QR',
    'cancel': 'Cancelar',
    'open': 'Abrir',
    'qrScannerTitle': 'Escáner de QR',
    'qrScannerHint': 'Apunta la cámara al código QR',
    'qrProcessing': 'Procesando...',
    'qrManualButton': 'Introducir código manualmente',
  },
  AppLanguage.french: {
    'chooseLanguageTitle': 'Choisissez votre langue',
    'chooseLanguageSubtitle': 'Sélectionnez votre langue préférée',
    'continueAction': 'Continuer',
    'profileLanguageTitle': 'Langue',
    'profileLanguageSubtitle': 'Langue de l’interface',
    'profileLanguagePickerTitle': 'Choisissez la langue',
    'onboardingSkip': 'Ignorer',
    'onboardingNext': 'Suivant',
    'onboardingStart': 'Commencer',
    'onboardingWelcomeTitle': 'Bienvenue dans ARient',
    'onboardingWelcomeDescription':
        'Explorez les métiers du futur avec des quêtes en réalité augmentée',
    'onboardingProfessionTitle': 'Plongez dans un métier',
    'onboardingProfessionDescription':
        'Essayez le rôle d’ingénieur, de médecin ou de designer en réalité augmentée',
    'onboardingAchievementsTitle': 'Gagnez des succès',
    'onboardingAchievementsDescription':
        'Terminez des quêtes, répondez aux questions et débloquez des récompenses',
    'navHome': 'Accueil',
    'navProfile': 'Profil',
    'profileJoinedEvents': 'Événements',
    'profileScannedQuests': 'Quêtes scannées',
    'profileAchievements': 'Succès',
    'profileRecentActivities': 'Activités récentes',
    'profileLogout': 'Se déconnecter',
    'profileLoadFailed': 'Impossible de charger le profil',
    'profileUnavailable': 'Profil indisponible',
    'genericError': 'Une erreur est survenue',
    'homeGreeting': 'Bonjour,',
    'homeEventsTitle': 'Mes événements',
    'homeEmptyEvents': 'Vous n’avez encore rejoint aucun événement.',
    'homeLoadFailed': 'Impossible de charger les événements',
    'loginSubtitle': 'Connectez-vous et commencez à explorer',
    'loginFieldLogin': 'Identifiant',
    'loginFieldPassword': 'Mot de passe',
    'loginButton': 'Se connecter',
    'loginQrButton': 'Se connecter avec un QR code',
    'loginNoAccount': 'Pas de compte ?',
    'loginRegisterLink': 'S’inscrire',
    'registerTitle': 'Inscription',
    'registerSubtitle': 'Créez un compte et commencez le voyage',
    'firstName': 'Prénom',
    'lastName': 'Nom',
    'registerButton': 'Créer un compte',
    'alreadyHaveAccount': 'Vous avez déjà un compte ?',
    'welcomeUser': 'Bienvenue, {login} !',
    'qrManualTitle': 'Saisir le QR code',
    'qrManualHint': 'Jeton ou valeur QR',
    'cancel': 'Annuler',
    'open': 'Ouvrir',
    'qrScannerTitle': 'Scanner de QR code',
    'qrScannerHint': 'Pointez la caméra vers le QR code',
    'qrProcessing': 'Traitement...',
    'qrManualButton': 'Saisir le code manuellement',
  },
  AppLanguage.hindi: {
    'chooseLanguageTitle': 'अपनी भाषा चुनें',
    'chooseLanguageSubtitle': 'अपनी पसंदीदा भाषा चुनें',
    'continueAction': 'जारी रखें',
    'profileLanguageTitle': 'भाषा',
    'profileLanguageSubtitle': 'ऐप इंटरफेस की भाषा',
    'profileLanguagePickerTitle': 'भाषा चुनें',
    'onboardingSkip': 'छोड़ें',
    'onboardingNext': 'आगे',
    'onboardingStart': 'शुरू करें',
    'onboardingWelcomeTitle': 'ARient में आपका स्वागत है',
    'onboardingWelcomeDescription':
        'ऑगमेंटेड रियलिटी क्वेस्ट के साथ भविष्य के पेशे खोजें',
    'onboardingProfessionTitle': 'पेशे में उतरें',
    'onboardingProfessionDescription':
        'ऑगमेंटेड रियलिटी में इंजीनियर, डॉक्टर या डिजाइनर की भूमिका आज़माएँ',
    'onboardingAchievementsTitle': 'उपलब्धियाँ पाएँ',
    'onboardingAchievementsDescription':
        'क्वेस्ट पूरे करें, सवालों के जवाब दें और नए पुरस्कार खोलें',
    'navHome': 'मुख्य',
    'navProfile': 'प्रोफ़ाइल',
    'profileJoinedEvents': 'इवेंट',
    'profileScannedQuests': 'स्कैन किए गए क्वेस्ट',
    'profileAchievements': 'उपलब्धियाँ',
    'profileRecentActivities': 'हाल की गतिविधियाँ',
    'profileLogout': 'लॉग आउट',
    'profileLoadFailed': 'प्रोफ़ाइल लोड नहीं हो सकी',
    'profileUnavailable': 'प्रोफ़ाइल उपलब्ध नहीं है',
    'genericError': 'कुछ गलत हो गया',
    'homeGreeting': 'नमस्ते,',
    'homeEventsTitle': 'मेरे इवेंट',
    'homeEmptyEvents': 'आप अभी तक किसी इवेंट से नहीं जुड़े हैं.',
    'homeLoadFailed': 'इवेंट लोड नहीं हो सके',
    'loginSubtitle': 'साइन इन करें और खोज शुरू करें',
    'loginFieldLogin': 'लॉगिन',
    'loginFieldPassword': 'पासवर्ड',
    'loginButton': 'साइन इन',
    'loginQrButton': 'QR कोड से साइन इन',
    'loginNoAccount': 'खाता नहीं है?',
    'loginRegisterLink': 'रजिस्टर करें',
    'registerTitle': 'रजिस्ट्रेशन',
    'registerSubtitle': 'खाता बनाएँ और यात्रा शुरू करें',
    'firstName': 'नाम',
    'lastName': 'उपनाम',
    'registerButton': 'खाता बनाएँ',
    'alreadyHaveAccount': 'पहले से खाता है?',
    'welcomeUser': 'स्वागत है, {login}!',
    'qrManualTitle': 'QR कोड दर्ज करें',
    'qrManualHint': 'टोकन या QR मान',
    'cancel': 'रद्द करें',
    'open': 'खोलें',
    'qrScannerTitle': 'QR कोड स्कैनर',
    'qrScannerHint': 'कैमरा QR कोड पर रखें',
    'qrProcessing': 'प्रोसेस हो रहा है...',
    'qrManualButton': 'कोड मैन्युअल रूप से दर्ज करें',
  },
  AppLanguage.indonesian: {
    'chooseLanguageTitle': 'Pilih Bahasa Anda',
    'chooseLanguageSubtitle': 'Pilih bahasa yang Anda inginkan',
    'continueAction': 'Lanjutkan',
    'profileLanguageTitle': 'Bahasa',
    'profileLanguageSubtitle': 'Bahasa antarmuka aplikasi',
    'profileLanguagePickerTitle': 'Pilih bahasa',
    'onboardingSkip': 'Lewati',
    'onboardingNext': 'Berikutnya',
    'onboardingStart': 'Mulai',
    'onboardingWelcomeTitle': 'Selamat datang di ARient',
    'onboardingWelcomeDescription':
        'Jelajahi profesi masa depan melalui quest AR',
    'onboardingProfessionTitle': 'Masuki sebuah profesi',
    'onboardingProfessionDescription':
        'Coba peran insinyur, dokter, atau desainer dalam augmented reality',
    'onboardingAchievementsTitle': 'Raih pencapaian',
    'onboardingAchievementsDescription':
        'Selesaikan quest, jawab pertanyaan, dan buka hadiah baru',
    'navHome': 'Beranda',
    'navProfile': 'Profil',
    'profileJoinedEvents': 'Acara',
    'profileScannedQuests': 'Quest dipindai',
    'profileAchievements': 'Pencapaian',
    'profileRecentActivities': 'Aktivitas terbaru',
    'profileLogout': 'Keluar',
    'profileLoadFailed': 'Profil tidak dapat dimuat',
    'profileUnavailable': 'Profil tidak tersedia',
    'genericError': 'Terjadi kesalahan',
    'homeGreeting': 'Halo,',
    'homeEventsTitle': 'Acara saya',
    'homeEmptyEvents': 'Anda belum bergabung dengan acara apa pun.',
    'homeLoadFailed': 'Acara tidak dapat dimuat',
    'loginSubtitle': 'Masuk dan mulai menjelajah',
    'loginFieldLogin': 'Login',
    'loginFieldPassword': 'Kata sandi',
    'loginButton': 'Masuk',
    'loginQrButton': 'Masuk dengan kode QR',
    'loginNoAccount': 'Belum punya akun?',
    'loginRegisterLink': 'Daftar',
    'registerTitle': 'Registrasi',
    'registerSubtitle': 'Buat akun dan mulai perjalanan',
    'firstName': 'Nama depan',
    'lastName': 'Nama belakang',
    'registerButton': 'Buat akun',
    'alreadyHaveAccount': 'Sudah punya akun?',
    'welcomeUser': 'Selamat datang, {login}!',
    'qrManualTitle': 'Masukkan kode QR',
    'qrManualHint': 'Token atau nilai QR',
    'cancel': 'Batal',
    'open': 'Buka',
    'qrScannerTitle': 'Pemindai kode QR',
    'qrScannerHint': 'Arahkan kamera ke kode QR',
    'qrProcessing': 'Memproses...',
    'qrManualButton': 'Masukkan kode manual',
  },
  AppLanguage.italian: {
    'chooseLanguageTitle': 'Scegli la lingua',
    'chooseLanguageSubtitle': 'Seleziona la lingua preferita',
    'continueAction': 'Continua',
    'profileLanguageTitle': 'Lingua',
    'profileLanguageSubtitle': 'Lingua dell’interfaccia',
    'profileLanguagePickerTitle': 'Scegli la lingua',
    'onboardingSkip': 'Salta',
    'onboardingNext': 'Avanti',
    'onboardingStart': 'Inizia',
    'onboardingWelcomeTitle': 'Benvenuto in ARient',
    'onboardingWelcomeDescription':
        'Esplora le professioni del futuro con quest in realtà aumentata',
    'onboardingProfessionTitle': 'Entra nella professione',
    'onboardingProfessionDescription':
        'Prova il ruolo di ingegnere, medico o designer in realtà aumentata',
    'onboardingAchievementsTitle': 'Ottieni obiettivi',
    'onboardingAchievementsDescription':
        'Completa quest, rispondi alle domande e sblocca nuove ricompense',
    'navHome': 'Home',
    'navProfile': 'Profilo',
    'profileJoinedEvents': 'Eventi',
    'profileScannedQuests': 'Quest scansionate',
    'profileAchievements': 'Obiettivi',
    'profileRecentActivities': 'Attività recenti',
    'profileLogout': 'Esci',
    'profileLoadFailed': 'Impossibile caricare il profilo',
    'profileUnavailable': 'Profilo non disponibile',
    'genericError': 'Qualcosa è andato storto',
    'homeGreeting': 'Ciao,',
    'homeEventsTitle': 'I miei eventi',
    'homeEmptyEvents': 'Non hai ancora partecipato a nessun evento.',
    'homeLoadFailed': 'Impossibile caricare gli eventi',
    'loginSubtitle': 'Accedi e inizia a esplorare',
    'loginFieldLogin': 'Login',
    'loginFieldPassword': 'Password',
    'loginButton': 'Accedi',
    'loginQrButton': 'Accedi con codice QR',
    'loginNoAccount': 'Non hai un account?',
    'loginRegisterLink': 'Registrati',
    'registerTitle': 'Registrazione',
    'registerSubtitle': 'Crea un account e inizia il viaggio',
    'firstName': 'Nome',
    'lastName': 'Cognome',
    'registerButton': 'Crea account',
    'alreadyHaveAccount': 'Hai già un account?',
    'welcomeUser': 'Benvenuto, {login}!',
    'qrManualTitle': 'Inserisci codice QR',
    'qrManualHint': 'Token o valore QR',
    'cancel': 'Annulla',
    'open': 'Apri',
    'qrScannerTitle': 'Scanner codice QR',
    'qrScannerHint': 'Punta la fotocamera sul codice QR',
    'qrProcessing': 'Elaborazione...',
    'qrManualButton': 'Inserisci codice manualmente',
  },
  AppLanguage.japanese: {
    'chooseLanguageTitle': '言語を選択',
    'chooseLanguageSubtitle': '使用する言語を選択してください',
    'continueAction': '続ける',
    'profileLanguageTitle': '言語',
    'profileLanguageSubtitle': 'アプリの表示言語',
    'profileLanguagePickerTitle': '言語を選択',
    'onboardingSkip': 'スキップ',
    'onboardingNext': '次へ',
    'onboardingStart': '開始',
    'onboardingWelcomeTitle': 'ARientへようこそ',
    'onboardingWelcomeDescription': 'ARクエストで未来の職業を体験しましょう',
    'onboardingProfessionTitle': '職業を体験',
    'onboardingProfessionDescription': 'ARでエンジニア、医師、デザイナーの役割を試せます',
    'onboardingAchievementsTitle': '実績を獲得',
    'onboardingAchievementsDescription': 'クエストを完了し、質問に答えて、新しい報酬を開放しましょう',
    'navHome': 'ホーム',
    'navProfile': 'プロフィール',
    'profileJoinedEvents': 'イベント',
    'profileScannedQuests': 'スキャンしたクエスト',
    'profileAchievements': '実績',
    'profileRecentActivities': '最近のアクティビティ',
    'profileLogout': 'ログアウト',
    'profileLoadFailed': 'プロフィールを読み込めませんでした',
    'profileUnavailable': 'プロフィールは利用できません',
    'genericError': '問題が発生しました',
    'homeGreeting': 'こんにちは、',
    'homeEventsTitle': '参加イベント',
    'homeEmptyEvents': 'まだイベントに参加していません。',
    'homeLoadFailed': 'イベントを読み込めませんでした',
    'loginSubtitle': 'ログインして探索を始めましょう',
    'loginFieldLogin': 'ログイン',
    'loginFieldPassword': 'パスワード',
    'loginButton': 'ログイン',
    'loginQrButton': 'QRコードでログイン',
    'loginNoAccount': 'アカウントがありませんか？',
    'loginRegisterLink': '登録',
    'registerTitle': '登録',
    'registerSubtitle': 'アカウントを作成して旅を始めましょう',
    'firstName': '名',
    'lastName': '姓',
    'registerButton': 'アカウント作成',
    'alreadyHaveAccount': 'すでにアカウントをお持ちですか？',
    'welcomeUser': 'ようこそ、{login}!',
    'qrManualTitle': 'QRコードを入力',
    'qrManualHint': 'トークンまたはQR値',
    'cancel': 'キャンセル',
    'open': '開く',
    'qrScannerTitle': 'QRコードスキャナー',
    'qrScannerHint': 'カメラをQRコードに向けてください',
    'qrProcessing': '処理中...',
    'qrManualButton': 'コードを手入力',
  },
  AppLanguage.korean: {
    'chooseLanguageTitle': '언어 선택',
    'chooseLanguageSubtitle': '사용할 언어를 선택하세요',
    'continueAction': '계속',
    'profileLanguageTitle': '언어',
    'profileLanguageSubtitle': '앱 인터페이스 언어',
    'profileLanguagePickerTitle': '언어 선택',
    'onboardingSkip': '건너뛰기',
    'onboardingNext': '다음',
    'onboardingStart': '시작',
    'onboardingWelcomeTitle': 'ARient에 오신 것을 환영합니다',
    'onboardingWelcomeDescription': 'AR 퀘스트로 미래 직업을 탐색하세요',
    'onboardingProfessionTitle': '직업 속으로 들어가기',
    'onboardingProfessionDescription': '증강 현실에서 엔지니어, 의사, 디자이너 역할을 체험하세요',
    'onboardingAchievementsTitle': '업적 획득',
    'onboardingAchievementsDescription': '퀘스트를 완료하고 질문에 답해 새로운 보상을 여세요',
    'navHome': '홈',
    'navProfile': '프로필',
    'profileJoinedEvents': '이벤트',
    'profileScannedQuests': '스캔한 퀘스트',
    'profileAchievements': '업적',
    'profileRecentActivities': '최근 활동',
    'profileLogout': '로그아웃',
    'profileLoadFailed': '프로필을 불러오지 못했습니다',
    'profileUnavailable': '프로필을 사용할 수 없습니다',
    'genericError': '문제가 발생했습니다',
    'homeGreeting': '안녕하세요,',
    'homeEventsTitle': '내 이벤트',
    'homeEmptyEvents': '아직 참여한 이벤트가 없습니다.',
    'homeLoadFailed': '이벤트를 불러오지 못했습니다',
    'loginSubtitle': '로그인하고 탐색을 시작하세요',
    'loginFieldLogin': '로그인',
    'loginFieldPassword': '비밀번호',
    'loginButton': '로그인',
    'loginQrButton': 'QR 코드로 로그인',
    'loginNoAccount': '계정이 없나요?',
    'loginRegisterLink': '가입하기',
    'registerTitle': '회원가입',
    'registerSubtitle': '계정을 만들고 여정을 시작하세요',
    'firstName': '이름',
    'lastName': '성',
    'registerButton': '계정 만들기',
    'alreadyHaveAccount': '이미 계정이 있나요?',
    'welcomeUser': '환영합니다, {login}!',
    'qrManualTitle': 'QR 코드 입력',
    'qrManualHint': '토큰 또는 QR 값',
    'cancel': '취소',
    'open': '열기',
    'qrScannerTitle': 'QR 코드 스캐너',
    'qrScannerHint': '카메라를 QR 코드에 맞추세요',
    'qrProcessing': '처리 중...',
    'qrManualButton': '코드 직접 입력',
  },
  AppLanguage.portuguese: {
    'chooseLanguageTitle': 'Escolha o idioma',
    'chooseLanguageSubtitle': 'Selecione seu idioma preferido',
    'continueAction': 'Continuar',
    'profileLanguageTitle': 'Idioma',
    'profileLanguageSubtitle': 'Idioma da interface',
    'profileLanguagePickerTitle': 'Escolha o idioma',
    'onboardingSkip': 'Pular',
    'onboardingNext': 'Avançar',
    'onboardingStart': 'Começar',
    'onboardingWelcomeTitle': 'Bem-vindo ao ARient',
    'onboardingWelcomeDescription':
        'Explore profissões do futuro com missões em realidade aumentada',
    'onboardingProfessionTitle': 'Entre na profissão',
    'onboardingProfessionDescription':
        'Experimente o papel de engenheiro, médico ou designer em realidade aumentada',
    'onboardingAchievementsTitle': 'Ganhe conquistas',
    'onboardingAchievementsDescription':
        'Complete missões, responda perguntas e desbloqueie recompensas',
    'navHome': 'Início',
    'navProfile': 'Perfil',
    'profileJoinedEvents': 'Eventos',
    'profileScannedQuests': 'Missões escaneadas',
    'profileAchievements': 'Conquistas',
    'profileRecentActivities': 'Atividades recentes',
    'profileLogout': 'Sair',
    'profileLoadFailed': 'Não foi possível carregar o perfil',
    'profileUnavailable': 'Perfil indisponível',
    'genericError': 'Algo deu errado',
    'homeGreeting': 'Olá,',
    'homeEventsTitle': 'Meus eventos',
    'homeEmptyEvents': 'Você ainda não entrou em nenhum evento.',
    'homeLoadFailed': 'Não foi possível carregar os eventos',
    'loginSubtitle': 'Entre e comece a explorar',
    'loginFieldLogin': 'Login',
    'loginFieldPassword': 'Senha',
    'loginButton': 'Entrar',
    'loginQrButton': 'Entrar com código QR',
    'loginNoAccount': 'Não tem conta?',
    'loginRegisterLink': 'Cadastrar',
    'registerTitle': 'Cadastro',
    'registerSubtitle': 'Crie uma conta e comece a jornada',
    'firstName': 'Nome',
    'lastName': 'Sobrenome',
    'registerButton': 'Criar conta',
    'alreadyHaveAccount': 'Já tem uma conta?',
    'welcomeUser': 'Bem-vindo, {login}!',
    'qrManualTitle': 'Inserir código QR',
    'qrManualHint': 'Token ou valor QR',
    'cancel': 'Cancelar',
    'open': 'Abrir',
    'qrScannerTitle': 'Scanner de QR',
    'qrScannerHint': 'Aponte a câmera para o código QR',
    'qrProcessing': 'Processando...',
    'qrManualButton': 'Inserir código manualmente',
  },
  AppLanguage.chinese: {
    'chooseLanguageTitle': '选择语言',
    'chooseLanguageSubtitle': '选择您的首选语言',
    'continueAction': '继续',
    'profileLanguageTitle': '语言',
    'profileLanguageSubtitle': '应用界面语言',
    'profileLanguagePickerTitle': '选择语言',
    'onboardingSkip': '跳过',
    'onboardingNext': '下一步',
    'onboardingStart': '开始',
    'onboardingWelcomeTitle': '欢迎使用 ARient',
    'onboardingWelcomeDescription': '通过增强现实任务探索未来职业',
    'onboardingProfessionTitle': '进入职业体验',
    'onboardingProfessionDescription': '在增强现实中尝试工程师、医生或设计师角色',
    'onboardingAchievementsTitle': '获得成就',
    'onboardingAchievementsDescription': '完成任务、回答问题并解锁新的奖励',
    'navHome': '首页',
    'navProfile': '个人资料',
    'profileJoinedEvents': '活动',
    'profileScannedQuests': '已扫描任务',
    'profileAchievements': '成就',
    'profileRecentActivities': '最近活动',
    'profileLogout': '退出登录',
    'profileLoadFailed': '无法加载个人资料',
    'profileUnavailable': '个人资料不可用',
    'genericError': '出了点问题',
    'homeGreeting': '你好，',
    'homeEventsTitle': '我的活动',
    'homeEmptyEvents': '你还没有加入任何活动。',
    'homeLoadFailed': '无法加载活动',
    'loginSubtitle': '登录并开始探索',
    'loginFieldLogin': '登录名',
    'loginFieldPassword': '密码',
    'loginButton': '登录',
    'loginQrButton': '使用二维码登录',
    'loginNoAccount': '没有账号？',
    'loginRegisterLink': '注册',
    'registerTitle': '注册',
    'registerSubtitle': '创建账号并开始旅程',
    'firstName': '名字',
    'lastName': '姓氏',
    'registerButton': '创建账号',
    'alreadyHaveAccount': '已有账号？',
    'welcomeUser': '欢迎，{login}!',
    'qrManualTitle': '输入二维码',
    'qrManualHint': '令牌或二维码值',
    'cancel': '取消',
    'open': '打开',
    'qrScannerTitle': '二维码扫描器',
    'qrScannerHint': '将摄像头对准二维码',
    'qrProcessing': '处理中...',
    'qrManualButton': '手动输入代码',
  },
};
